services:
  web:
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - database
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  worker:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - database
    command: bin/jobs
volumes:
  bundle:
