services:
  web:
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - database
      - redis
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  sidekiq:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - database
      - redis
    command: bundle exec sidekiq
  tailwindcss:
    build: .
    volumes:
      - .:/app
    command: bin/rails tailwindcss:watch[always]
volumes:
  redis:
  bundle:
