default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: [ default ]
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 3) %>
      polling_interval: 1
    - queues: [ disco ]
      threads: 1
      processes: 1
      polling_interval: 2

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
