name: Auto Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: docker compose build

      - name: Setup database
        run: docker compose run --rm web ./bin/rails db:test:prepare

      - name: Run tests
        run: docker compose run --rm web ./bin/rails test 
